// napolitana, muzzarella, fugazzeta, cuatro quesos y calabresa
const arPizzas= [ {id:1, imagen:"img/pizzamuzzarella.jpg",gusto:"Pizza Muzzarella", tamaño:"Pizza grande", precio:2000},
                {id:2, imagen:"img/pizzanapolitana.jpg", gusto:"Pizza Napolitana", tamaño:"Pizza grande", precio:2100},
                {id:3, imagen:"img/pizzafugazzeta.jpg", gusto:"Pizza Fugazzeta", tamaño:"Pizza grande", precio:2200},
                {id:4, imagen:"img/pizzacalabresa.jpg", gusto:"Pizza Calabresa", tamaño:"Pizza grande", precio:2200},
                {id:5, imagen:"img/pizzacuatroquesos.avif", gusto:"Pizza Cuatro quesos", tamaño:"Pizza grande", precio:2250},
                {id:6, imagen:"img/pizzaruculayjamoncrudo.jpg", gusto:"Pizza Rucula y jamon crudo", tamaño:"Pizza grande", precio:2200},
                {id:7, imagen:"img/pizzamuzzayanchoas.jpg", gusto:"Pizza Anchoas", tamaño:"Pizza grande", precio:2350},
                {id:8, imagen:"img/pizzaespinacaysalsablanca.jpg", gusto:"Pizza Espinaca y salsa blanca", tamaño:"Pizza grande", precio:2200},
                {id:9, imagen:"img/pizzaquesojamonyhuevo.jpg", gusto:"Pizza con huevo", tamaño:"Pizza grande", precio:2250},
                {id:10, imagen:"img/pizzaconmorron.jpg", gusto:"Pizza con morron", tamaño:"Pizza grande", precio:2250},
                {id:11, imagen:"img/pizzaespecialdulce.jpg", gusto:"Pizza Especial dulce", tamaño:"Pizza grande", precio:2300},
                {id:12,imagen:"img/pizzamuzzarellachica.webp",gusto:"Pizza Muzzarella", tamaño:"Pizza chica", precio:1100},
                {id:13, imagen:"img/pizzanapolitana.jpg", gusto:"Pizza Napolitana", tamaño:"Pizza chica", precio:1200},
                {id:14, imagen:"img/pizzafugazzeta.jpg", gusto:"Pizza Fugazzeta", tamaño:"Pizza chica", precio:1300},
                {id:15, imagen:"img/pizzacalabresachica.jpg", gusto:"Pizza Calabresa", tamaño:"Pizza chica", precio:1300},
                {id:16, imagen:"img/pizzacuatroquesos.avif", gusto:"Pizza Cuatro quesos", tamaño:"Pizza chica", precio:1350},
                {id:17, imagen:"img/pizzaruculayjamoncrudo.jpg", gusto:"Pizza Rucula y jamon crudo", tamaño:"Pizza chica", precio:1300},
                {id:18, imagen:"img/pizzamuzzayanchoas.jpg", gusto:"Pizza Anchoas", tamaño:"Pizza chica", precio:1450},
                {id:19, imagen:"img/pizzaespinacaysalsablanca.jpg", gusto:"Pizza Espinaca y salsa blanca", tamaño:"Pizza chica", precio:1200},
                {id:20, imagen:"img/pizzaquesojamonyhuevo.jpg", gusto:"Pizza con huevo", tamaño:"Pizza chica", precio:1250},
                {id:21, imagen:"img/pizzaconmorron.jpg", gusto:"Pizza con morron", tamaño:"Pizza chica", precio:1250},
                {id:22, imagen:"img/pizzaespecialdulce.jpg", gusto:"Pizza Especial dulce", tamaño:"Pizza chica", precio:1400}];

